// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VGL.Data;

#nullable disable

namespace GameLogBook.Migrations
{
    [DbContext(typeof(GameLogBookDbContext))]
    [Migration("20260528135310_AddAppSettings")]
    partial class AddAppSettings
    {
    }
}
