// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VGL.Data;

#nullable disable

namespace VGL.Migrations
{
    [DbContext(typeof(GameLogBookDbContext))]
    [Migration("20260523170915_updatetogameplatform")]
    partial class updatetogameplatform
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GameLogBook.Models.Companies.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IgdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("ID IS NOT NULL");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("GameLogBook.Models.Games.Company.GameCompany", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameID", "CompanyID", "Role");

                    b.HasIndex("CompanyID");

                    b.ToTable("GameCompanies");
                });

            modelBuilder.Entity("GameLogBook.Models.Games.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IgdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameLogBook.Models.Games.Platform.GamePlatform", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatformID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ownership")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameID", "PlatformID", "Ownership");

                    b.HasIndex("PlatformID");

                    b.ToTable("GamePlatform");
                });

            modelBuilder.Entity("GameLogBook.Models.Platforms.Platform", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("IgdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ManufacturerIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("ID IS NOT NULL");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("GameLogBook.Models.Playthrough", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("GameIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Playthroughs");
                });

            modelBuilder.Entity("GameLogBook.Models.Games.Company.GameCompany", b =>
                {
                    b.HasOne("GameLogBook.Models.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameLogBook.Models.Games.Game", "Game")
                        .WithMany("GameCompanies")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameLogBook.Models.Games.Game", b =>
                {
                    b.OwnsOne("GameLogBook.Models.Games.Cover", "Cover", b1 =>
                        {
                            b1.Property<int>("GameId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ImagePath")
                                .HasColumnType("TEXT");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("GameLogBook.Models.Games.Platform.GamePlatform", b =>
                {
                    b.HasOne("GameLogBook.Models.Games.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLogBook.Models.Platforms.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameLogBook.Models.Games.Game", b =>
                {
                    b.Navigation("GameCompanies");

                    b.Navigation("GamePlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
