// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VGL.Data;

#nullable disable

namespace VGL.Migrations
{
    [DbContext(typeof(GameLogBookDbContext))]
    [Migration("20260530154036_MakeGameLogEndOptional")]
    partial class MakeGameLogEndOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("VGL.Models.Companies.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FoundedDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IGDB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("ID IS NOT NULL");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("VGL.Models.Configuration.AppSettings", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamGridDbApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("VGL.Models.GameLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaythroughID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("PlatformID");

                    b.HasIndex("PlaythroughID");

                    b.HasIndex("UserProfileID", "StartedAt");

                    b.ToTable("GameLogs");
                });

            modelBuilder.Entity("VGL.Models.Games.Company.GameCompany", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameID", "CompanyID", "Role");

                    b.HasIndex("CompanyID");

                    b.ToTable("GameCompanies");
                });

            modelBuilder.Entity("VGL.Models.Games.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IGDB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("VGL.Models.Platforms.Company.PlatformCompany", b =>
                {
                    b.Property<int>("PlatformID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlatformID", "CompanyID", "Role");

                    b.HasIndex("CompanyID");

                    b.ToTable("PlatformCompanies");
                });

            modelBuilder.Entity("VGL.Models.Platforms.Platform", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IGDB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("ID IS NOT NULL");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("VGL.Models.Playthrough", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ManualFinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ManualMasteredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ManualStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlatformID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlaythroughRunID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("PlatformID");

                    b.HasIndex("PlaythroughRunID");

                    b.HasIndex("UserProfileID", "Status");

                    b.ToTable("Playthroughs");
                });

            modelBuilder.Entity("VGL.Models.PlaythroughRun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserProfileID", "Name");

                    b.ToTable("PlaythroughRuns");
                });

            modelBuilder.Entity("VGL.Models.Users.UserGameCollection", b =>
                {
                    b.Property<int>("UserProfileID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserProfileID", "GameID");

                    b.HasIndex("GameID");

                    b.ToTable("UserGameCollections");
                });

            modelBuilder.Entity("VGL.Models.Users.UserGamePlatformOwnership", b =>
                {
                    b.Property<int>("UserProfileID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatformID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ownership")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserProfileID", "GameID", "PlatformID", "Ownership");

                    b.HasIndex("GameID");

                    b.HasIndex("PlatformID");

                    b.ToTable("UserGamePlatformOwnerships");
                });

            modelBuilder.Entity("VGL.Models.Users.UserPlatformCollection", b =>
                {
                    b.Property<int>("UserProfileID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatformID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserProfileID", "PlatformID");

                    b.HasIndex("PlatformID");

                    b.ToTable("UserPlatformCollections");
                });

            modelBuilder.Entity("VGL.Models.Users.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("VGL.Models.Companies.Company", b =>
                {
                    b.OwnsOne("VGL.Models.ImageRef", "Cover", b1 =>
                        {
                            b1.Property<int>("CompanyID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("CompanyID");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyID");
                        });

                    b.OwnsOne("VGL.Models.ImageRef", "Hero", b1 =>
                        {
                            b1.Property<int>("CompanyID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("CompanyID");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyID");
                        });

                    b.OwnsOne("VGL.Models.ImageRef", "Icon", b1 =>
                        {
                            b1.Property<int>("CompanyID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("CompanyID");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyID");
                        });

                    b.OwnsOne("VGL.Models.ImageRef", "Logo", b1 =>
                        {
                            b1.Property<int>("CompanyID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("CompanyID");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyID");
                        });

                    b.Navigation("Cover");

                    b.Navigation("Hero");

                    b.Navigation("Icon");

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("VGL.Models.GameLog", b =>
                {
                    b.HasOne("VGL.Models.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VGL.Models.Platforms.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VGL.Models.Playthrough", "Playthrough")
                        .WithMany("Logs")
                        .HasForeignKey("PlaythroughID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VGL.Models.Users.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");

                    b.Navigation("Playthrough");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("VGL.Models.Games.Company.GameCompany", b =>
                {
                    b.HasOne("VGL.Models.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VGL.Models.Games.Game", "Game")
                        .WithMany("GameCompanies")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("VGL.Models.Games.Game", b =>
                {
                    b.OwnsOne("VGL.Models.ImageRef", "Cover", b1 =>
                        {
                            b1.Property<int>("GameID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("GameID");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameID");
                        });

                    b.OwnsOne("VGL.Models.ImageRef", "Hero", b1 =>
                        {
                            b1.Property<int>("GameID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("GameID");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameID");
                        });

                    b.OwnsOne("VGL.Models.ImageRef", "Icon", b1 =>
                        {
                            b1.Property<int>("GameID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("GameID");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameID");
                        });

                    b.OwnsOne("VGL.Models.ImageRef", "Logo", b1 =>
                        {
                            b1.Property<int>("GameID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("GameID");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameID");
                        });

                    b.Navigation("Cover");

                    b.Navigation("Hero");

                    b.Navigation("Icon");

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("VGL.Models.Platforms.Company.PlatformCompany", b =>
                {
                    b.HasOne("VGL.Models.Companies.Company", "Company")
                        .WithMany("PlatformCompanies")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VGL.Models.Platforms.Platform", "Platform")
                        .WithMany("PlatformCompanies")
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("VGL.Models.Platforms.Platform", b =>
                {
                    b.OwnsOne("VGL.Models.ImageRef", "Cover", b1 =>
                        {
                            b1.Property<int>("PlatformID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("PlatformID");

                            b1.ToTable("Platforms");

                            b1.WithOwner()
                                .HasForeignKey("PlatformID");
                        });

                    b.OwnsOne("VGL.Models.ImageRef", "Hero", b1 =>
                        {
                            b1.Property<int>("PlatformID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("PlatformID");

                            b1.ToTable("Platforms");

                            b1.WithOwner()
                                .HasForeignKey("PlatformID");
                        });

                    b.OwnsOne("VGL.Models.ImageRef", "Icon", b1 =>
                        {
                            b1.Property<int>("PlatformID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("PlatformID");

                            b1.ToTable("Platforms");

                            b1.WithOwner()
                                .HasForeignKey("PlatformID");
                        });

                    b.OwnsOne("VGL.Models.ImageRef", "Logo", b1 =>
                        {
                            b1.Property<int>("PlatformID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("PlatformID");

                            b1.ToTable("Platforms");

                            b1.WithOwner()
                                .HasForeignKey("PlatformID");
                        });

                    b.Navigation("Cover");

                    b.Navigation("Hero");

                    b.Navigation("Icon");

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("VGL.Models.Playthrough", b =>
                {
                    b.HasOne("VGL.Models.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VGL.Models.Platforms.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VGL.Models.PlaythroughRun", "PlaythroughRun")
                        .WithMany("Playthroughs")
                        .HasForeignKey("PlaythroughRunID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VGL.Models.Users.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");

                    b.Navigation("PlaythroughRun");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("VGL.Models.PlaythroughRun", b =>
                {
                    b.HasOne("VGL.Models.Users.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("VGL.Models.Users.UserGameCollection", b =>
                {
                    b.HasOne("VGL.Models.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VGL.Models.Users.UserProfile", "UserProfile")
                        .WithMany("Games")
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("VGL.Models.Users.UserGamePlatformOwnership", b =>
                {
                    b.HasOne("VGL.Models.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VGL.Models.Platforms.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VGL.Models.Users.UserProfile", "UserProfile")
                        .WithMany("GamePlatformOwnerships")
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("VGL.Models.Users.UserPlatformCollection", b =>
                {
                    b.HasOne("VGL.Models.Platforms.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VGL.Models.Users.UserProfile", "UserProfile")
                        .WithMany("Platforms")
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("VGL.Models.Users.UserProfile", b =>
                {
                    b.OwnsOne("VGL.Models.ImageRef", "ProfilePicture", b1 =>
                        {
                            b1.Property<int>("UserProfileID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Path")
                                .HasColumnType("TEXT");

                            b1.HasKey("UserProfileID");

                            b1.ToTable("UserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileID");
                        });

                    b.Navigation("ProfilePicture");
                });

            modelBuilder.Entity("VGL.Models.Companies.Company", b =>
                {
                    b.Navigation("PlatformCompanies");
                });

            modelBuilder.Entity("VGL.Models.Games.Game", b =>
                {
                    b.Navigation("GameCompanies");
                });

            modelBuilder.Entity("VGL.Models.Platforms.Platform", b =>
                {
                    b.Navigation("PlatformCompanies");
                });

            modelBuilder.Entity("VGL.Models.Playthrough", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("VGL.Models.PlaythroughRun", b =>
                {
                    b.Navigation("Playthroughs");
                });

            modelBuilder.Entity("VGL.Models.Users.UserProfile", b =>
                {
                    b.Navigation("GamePlatformOwnerships");

                    b.Navigation("Games");

                    b.Navigation("Platforms");
                });
#pragma warning restore 612, 618
        }
    }
}
